### ISSUE TITLE
PearlHandler Crash

### ISSUE THREAD

**Issue by ManiakMCPE** [Bavfalcon9/Mavoric#81] opened 2020-08-01 16:26 UTC
PocketMine-MP Crash Dump Sat Aug 1 16:18:44 UTC 2020

Error: Nesting level too deep - recursive dependency?
File: plugins/Mavoric.phar/src/Bavfalcon9/Mavoric/Core/Handlers/PearlHandler
Line: 83
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Mavoric v1.0.5

Code:
[74] 
[75]     /
[76]      * Clears throws from memory for performance reasons.
[77]      * @return void
[78]      */
[79]     public function purge(): void {
[80]         $purged = 0;
[81]         foreach ($this->throws as &$throw) {
[82]             if ($throw->getLandingTime() + 10 <= time()) {
[83]                 unset($this->throws[array_search($throw, $this->throws)]);
[84]                 $purged++;
[85]             }
[86]         }
[87]         return;
[88]     }
[89] 
[90]     /
[91]      * Returns a list of throws from a player
[92]      * @param String $player - Player name
[93]      * @return PearlThrow[] - Array of throws

01.08 12:13:09 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\math\Vector3::distance() must be an instance of pocketmine\math\Vector3, null given, called in phar:///plugins/Mavoric.phar/src/Bavfalcon9/Mavoric/Core/Detections/Reach.php on line 64" (EXCEPTION) in "vendor/pocketmine/math/src/Vector3" at line 260

**Comment by Bavfalcon9** [comment] 2020-08-01 16:41
Duplicate of #60

**Closed by Bavfalcon9** 2020-08-01 16:41 UTC
Labels: Bug, Duplicate
