### ISSUE TITLE
[BUG] Internal server error when slappers are used

### ISSUE THREAD

**Issue by TNT10128** [Bavfalcon9/Mavoric#77] opened 2020-07-08 22:59 UTC
## Description
When I have this plugin and the Slapper plugin installed, I can't click on any slapper NPCs set up on my server.
When I do, it kicks me for an internal server error.

**Additional context**
Console output on error:
```
[22:51:23] [Server thread/DEBUG]: #0 plugins/mavoric.phar/src/Bavfalcon9/Mavoric/Mavoric(214): Bavfalcon9\Mavoric\Core\Detections\MultiAura->onEvent(object Bavfalcon9\Mavoric\Events\player\PlayerAttack)

[22:51:23] [Server thread/DEBUG]: #1 plugins/mavoric.phar/src/Bavfalcon9/Mavoric/Events/EventHandler(197): Bavfalcon9\Mavoric\Mavoric->broadcastEvent(object Bavfalcon9\Mavoric\Events\player\PlayerAttack)

[22:51:23] [Server thread/DEBUG]: #2 src/pocketmine/plugin/MethodEventExecutor(42): Bavfalcon9\Mavoric\Events\EventHandler->onEntityDamage(object pocketmine\event\entity\EntityDamageByEntityEvent)

[22:51:23] [Server thread/DEBUG]: #3 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Bavfalcon9\Mavoric\Events\EventHandler, object pocketmine\event\entity\EntityDamageByEntityEvent)

[22:51:23] [Server thread/DEBUG]: #4 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)

[22:51:23] [Server thread/DEBUG]: #5 src/pocketmine/entity/Entity(932): pocketmine\event\Event->call()

[22:51:23] [Server thread/DEBUG]: #6 src/pocketmine/Player(2685): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)

[22:51:23] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(150): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)

[22:51:23] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(173): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)

[22:51:23] [Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)

[22:51:23] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)

[22:51:23] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)

[22:51:23] [Server thread/DEBUG]: #12 src/pocketmine/Player(3247): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)

[22:51:23] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)

[22:51:23] [Server thread/DEBUG]: #14 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 69.127.145.158 55836, object raklib\protocol\EncapsulatedPacket, integer 0)

[22:51:23] [Server thread/DEBUG]: #15 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()

[22:51:23] [Server thread/DEBUG]: #16 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()

[22:51:23] [Server thread/DEBUG]: #17 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()

[22:51:23] [Server thread/DEBUG]: #18 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()

[22:51:23] [Server thread/DEBUG]: #19 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1594248683.8231)

[22:51:23] [Server thread/DEBUG]: #20 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()

[22:51:23] [Server thread/DEBUG]: #21 src/pocketmine/Server(1588): pocketmine\Server->start()

[22:51:23] [Server thread/DEBUG]: #22 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[15] /home/gs-40766/, string[23] /home/gs-40766/plugins/)

[22:51:23] [Server thread/DEBUG]: #23 src/pocketmine/PocketMine(304): pocketmine\server()

[22:51:23] [Server thread/DEBUG]: #24 (11): require(string[94] phar:///pro/bin/mcpe/pocketmine-stable-1.16.0/PocketMine-MP.phar/src/pocketmine/)

```

**Comment by Bavfalcon9** [comment] 2020-07-08 23:05
Duplicate of #66

**Closed** 2020-12-12 18:31 UTC
Labels: Archived, Bug, Duplicate
